"""add_timestamps

Revision ID: 210e5e270f26
Revises: afc7593247d4
Create Date: 2025-08-10 13:34:25.999953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210e5e270f26'
down_revision: Union[str, Sequence[str], None] = 'afc7593247d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('interviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('responses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'created_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('interviews', 'created_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('businesses', 'created_at')
    # ### end Alembic commands ###
