"""add_employee_id_to_interviews

Revision ID: a76c22eeaf1e
Revises: 210e5e270f26
Create Date: 2025-08-10 15:09:06.185787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76c22eeaf1e'
down_revision: Union[str, Sequence[str], None] = '210e5e270f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('employee_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'interviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'employee_id')
    # ### end Alembic commands ###
