"""question_order_index

Revision ID: afc7593247d4
Revises: df0dfffeea17
Create Date: 2025-08-10 12:56:26.737963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc7593247d4'
down_revision: Union[str, Sequence[str], None] = 'df0dfffeea17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.add_column('questions', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order_index')
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
