site_name: Application Documentation
theme:
  name: material
  features:
  - navigation.expand
  - navigation.top
  - search.highlight
  - search.share
  - content.code.copy
nav:
markdown_extensions:
- tables
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- admonition
- pymdownx.details
- attr_list
- md_in_html
plugins:
- search
- render_swagger
